services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      - ./fixtures:/etc/localstack/init/fixtures
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - ahwr-local

  mongodb:
    image: mongo:7.0.28
    networks:
      - ahwr-local
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
      - ./compose/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./compose/DevNewWorldApplications.json:/temp/DevNewWorldApplications.json:ro
      - ./compose/DevOldWorldApplications.json:/temp/DevOldWorldApplications.json:ro
      - ./compose/DevClaims.json:/temp/DevClaims.json:ro
    restart: always

  ahwr-application-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      APPLICATION_BACKEND_QUEUE_URL: 'http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ahwr_application_backend_queue'
      DOCUMENT_REQUEST_TOPIC_ARN: 'arn:aws:sns:eu-west-2:000000000000:ahwr_document_request'
      REMINDER_REQUEST_TOPIC_ARN: 'arn:aws:sns:eu-west-2:000000000000:ahwr_reminder_request'
      STATUS_CHANGE_TOPIC_ARN: 'arn:aws:sns:eu-west-2:000000000000:ahwr_status_change'
      REMINDER_EMAIL_MAX_BATCH_SIZE: ${REMINDER_EMAIL_MAX_BATCH_SIZE:-5000}
      PROCESS_ON_HOLD_SCHEDULE: '*/2 * * * *'
      DATA_REDACTION_SCHEDULE: '0 0 1 */3 *'
      REMINDER_EMAILS_SCHEDULE: '0 0 1 */3 *'
      PUBLIC_UI_API_KEY: 'dbd47daf-2711-4cb6-b733-0bd60fdb3ce6'
      BACKOFFICE_UI_API_KEY: '446dcdbe-e02c-4d16-a266-001bbbd5f089'
    networks:
      - ahwr-local
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
      - ./.env:/home/node/.env

volumes:
  mongodb-data:

# Make sure you run 'docker network create ahwr-local' so you have this network locally
networks:
  ahwr-local:
    external: true
    name: ahwr-local
